services:
  dbmysql:
    container_name: mysql-wp
    image: mysql
    volumes:
       - $PWD/data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: welcome1
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    networks:
      - wp_net

  wp:
    container_name: wordpress
    volumes:
      - "$PWD/html:/var/www/html"
    depends_on:
      - dbmysql
    image: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: dbmysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wp_net
networks:
  wp_net:
